openapi: 3.0.3
info:
  description: APIs for closing vacancies and managing candidate status
  title: Close Vacancies API
  version: '1.0.0'

servers:
  - url: http://localhost:8080/api
    description: Base path of the API

tags:
  - name: CloseVacanciesAPI
    description: APIs for managing vacancies and candidate status

paths:
  /vacancies/{id}/close:
    post:
      summary: Close a vacancy
      tags:
        - CloseVacanciesAPI
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Vacancy closed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMessage'
        '404':
          description: Vacancy not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMessage'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMessage'

  /candidates/{id}/status:
    post:
      summary: Update candidate status
      tags:
        - CloseVacanciesAPI
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [rejected, parked]
                  example: rejected
      responses:
        '200':
          description: Candidate status updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMessage'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMessage'
        '404':
          description: Candidate not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMessage'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseMessage'

components:
  schemas:
    ResponseMessage:
      type: object
      properties:
        message:
          type: string
          example: Vacancy closed successfully
